### ISSUE TITLE
Сделать фильтрацию по типу url адресов

### ISSUE THREAD

**Issue by sergei4e** [sergei4e/sitest#1]
На странице site/urls

Выводится список адресов:

[ 200 ] www_ua.all.biz/news-rating
[ 200 ] http://_www.ua.all.biz/news
[ 200 ] http://_www.ua.all.biz/pochemu-uvolen-menedzhment-datagrup-intervyu-s-**n**411454
[ 200 ] http://_www.ua.all.biz/nedvizhimost-**nr**9
[ 200 ] http://_www.ua.all.biz/sharovoj-kran-dlya-gaza-so-standartnym-prohodom-**ob**8069311
[ 200 ] http://_www.ua.all.biz/sharovoj-kran-dlya-gaza-so-standartnym-prohodom-**ob**8069311?section_id=290&page=3 
 [ 200 ] http://_www.ru.all.biz/stroitelstvo-karkasnyh-domov-**s**367203
[ 200 ] http://_www.ru.all.biz/uk/santeh-ooo-**e**83535
[ 200 ] http://_www.ru.all.biz/santeh-ooo-**e**83535
[ 200 ] http://_www.ru.all.biz/en/construction-**bsr**1397
[ 200 ] http://_www.ru.all.biz/uk/budivelni-poslugy-**bsc**1925?other_country=0
[ 200 ] http://_www.ru.all.biz/en/
[ 200 ] http://_www.ru.all.biz/pl/sprzet-grzewniczy-**bgr**703/fltr-0-110
[ 200 ] http://_www.ru.all.biz/en/automobile-equipment-and-tuning-**epr**1855?page=2
[ 200 ] http://_www.ru.all.biz/en/construction-**bsr**1397?other_country=0 

В данных url адресах есть некая типизация. То что выделено - это как раз то что отличает типы страниц.

Задача:
Сделать так, чтобы на вкладке site/urls была возможность отфильтровать и посмотреть список только одного типа из **bgg**, **bgc**, **g**, **s**, **bgr** типов страниц.

Помогут регулярные выражения и еще один get параметр.

**Comment by yonjuuni** [comment]
Added in https://github.com/sergei4e/Sitest/commit/cc4832f2e1173524709ba197a243765d6b25dde3
